### ISSUE TITLE
make enkei cycle through wallpapers in a folder,

### ISSUE THREAD

**Issue by boatinalamp** [jwuensche/enkei#3]
so i have a folder with wallpapers in it, i would like to make enkei cycle through those wallpapers every 5-10 minutes. is this possible? and how?

**Comment by fia0** [comment]
The easiest solutions for this is to just create a wallpaper xml file with https://github.com/maoschanz/dynamic-wallpaper-editor.

With Dynamic Wallpaper Editor you can add a complete folder and set that all have the same duration.

![image](https://user-images.githubusercontent.com/23524191/189482513-ff874b14-5620-421a-ba5b-6b3b1db0c238.png)

Once done you can pick how long each image should show and how long the transition blending should last.

![image](https://user-images.githubusercontent.com/23524191/189482535-216262a4-f7fb-4e07-a297-4c1cd61b08d6.png)

When you're done simply start `enkei` with the saved xml file:
```
$ enkei my_cool_wallpapers.xml
```
or change the wallpaper while enkei is running:
```
$ enkeictl my_cool_wallpapers.xml
```

**Comment by boatinalamp** [comment]
im a bit late but enkei is an amazing tool! i use it on all my linux installs to date. and this solution worked perfectly!
